- src/commands/metta.py
- src/commands/server.py
- src/config/config.py
- src/services/__init__.py
- src/services/loader_container_service.py
> [#33] Remove poc loader

- .github/workflows/build.yml
> [#37] Create pipeline to deploy deb packages to vultr

- CHANGELOG
- README.md
> [#30] Documentation on how to download DAS CLI deb package

- src/commands/faas.py
- src/services/__init__.py
- src/services/image_service.py
> [#44] Faas start optional parameter

- .github/workflows/build.yml
> [#47] Remove v prefix

- README.md
- src/commands/__init__.py
- src/commands/example.py
- src/commands/release_notes.py
- src/config/config.py
- src/das_cli.py
- src/services/__init__.py
- src/services/release_notes_service.py
- src/utils/__init__.py
> [#51] Add minor features to das-cli and update documentation

- CHANGELOG
- src/services/container_service.py
- src/services/loader_container_service.py
- src/services/metta_parser_container_service.py
> [#51] Show validate and syntax check logs

- CHANGELOG
- src/das_cli.py
> [#59] Fix das-cli --version output message

- .github/workflows/build.yml
Closes https://github.com/singnet/das/issues/6
> [das#6] Migrate contents of das-scripts-pipeline to das

- src/commands/faas.py
- src/commands/python_library.py
- src/services/image_service.py
> [#72] das-cli python-library version is raising an error

- .github/workflows/build.yml
- CHANGELOG
Closes https://github.com/singnet/das/issues/22
> [das#22] Add title and deliverable message to versioning job

- CHANGELOG
- src/commands/config.py
- src/commands/faas.py
- src/config/config.py
- src/enums/__init__.py
- src/enums/function_enum.py
- src/services/image_service.py
- src/services/openfaas_container_service.py
> [#71] Put version number in openfaas docker image name

- .dockerignore
- CHANGELOG
- src/commands/config.py
- src/commands/db.py
- src/commands/faas.py
- src/commands/jupyter_notebook.py
- src/commands/logs.py
- src/commands/metta.py
- src/commands/python_library.py
- src/das_cli.py
- src/exceptions.py
- src/requirements.txt
- src/services/__init__.py
- src/services/container_remote_service.py
- src/services/container_service.py
- src/services/mongo_container_service.py
- src/services/openfaas_container_service.py
- src/services/redis_container_service.py
- src/utils/__init__.py
- src/utils/network.py
- src/utils/parsers.py
> [#75] Enable the configuration of a Redis cluster instead of maintaining only a standalone instance

- src/common/__init__.py
- src/common/command.py
- src/common/docker/__init__.py
- src/common/docker/container_manager.py
- src/common/docker/exceptions.py
- src/common/docker/image_manager.py
- src/common/docker/remote_context_manager.py
- src/common/json_handler.py
- src/common/logger.py
- src/common/module.py
- src/common/network.py
- src/common/prompt_types.py
- src/common/settings.py
- src/common/utils.py
> [#79] Refactor common classes

- src/config/config.py
- src/config/secrets.py
- src/das_cli.py
- src/setup.py
> [#79][#78] Improved logging capture from das-cli and replaced the old structure with the new one.

- src/commands/metta/metta_cli.py
> [#88] fixing some errors when running metta commands

- src/commands/logs/logs_cli.py
> [#90] fixing OpenFaaSContainerManager instantiation in LogsFaaS

- .github/workflows/build.yml
- .github/workflows/run-tests.yml
Closes https://github.com/singnet/das/issues/56
> [#56] Review release process

- tests/integration/libs/docker.bash
- tests/integration/test_faas.bats
> [#101] "das-cli faas update version" is not getting latest version

- src/commands/das/das_cli.py
- tests/integration/test_update_version.bats
> [#98] Change error message of commands that expects sudo

- CHANGELOG
- README.md
- src/commands/faas/faas_cli.py
- src/commands/faas/openfaas_container_manager.py
- tests/integration/libs/utils.bash
- tests/integration/test_faas.bats
Closes https://github.com/singnet/das/issues/66
> [das#66] Connecting to server error

- src/commands/jupyter_notebook/jupyter_notebook_cli.py
- src/commands/metta/metta_cli.py
- src/common/prompt_types.py
- tests/integration/test_jupyter_notebook.bats
- tests/integration/test_metta.bats
> [#123] Add validation for relative path in das-cli

- CHANGELOG
- src/commands/db/db_cli.py
- src/commands/db/db_module.py
- src/commands/db/mongodb_container_manager.py
- src/commands/db/redis_container_manager.py
- src/common/decorators.py
- tests/integration/test_db.bats
> [#122] Add a das-cli command to print the total number of atoms in the AtomDB

- CHANGELOG
- src/commands/db/db_cli.py
- src/commands/db/mongodb_container_manager.py
- tests/integration/test_db.bats
> [#132]: das-cli db count-atoms --verbose should detail Node and Link counts

- src/commands/config/config_cli.py
- src/common/docker/remote_context_manager.py
> [#139] das-cli have issues establishing an SSH connection to the cluster

- CHANGELOG
- src/commands/db/db_cli.py
- src/commands/db/redis_container_manager.py
- src/common/network.py
> [#141] Verify port range for Redis Cluster instead of a single port

- README.md
> [#114]: Add temporary directory creation error

- .github/workflows/run-das-cli-tests.yml
- das-cli/src/commands/attention_broker/__init__.py
- das-cli/src/commands/attention_broker/attention_broker_cli.py
- das-cli/src/commands/attention_broker/attention_broker_container_manager.py
- das-cli/src/commands/attention_broker/attention_broker_module.py
- das-cli/src/commands/config/config_cli.py
- das-cli/src/commands/link_creation_agent/__init__.py
- das-cli/src/commands/link_creation_agent/link_creation_agent_cli.py
- das-cli/src/commands/link_creation_agent/link_creation_agent_container_manager.py
- das-cli/src/commands/link_creation_agent/link_creation_agent_module.py
- das-cli/src/commands/query_agent/__init__.py
- das-cli/src/commands/query_agent/query_agent_cli.py
- das-cli/src/commands/query_agent/query_agent_container_manager.py
- das-cli/src/commands/query_agent/query_agent_module.py
- das-cli/src/common/docker/container_manager.py
- das-cli/src/das_cli.py
- das-cli/src/settings/config.py
- das-cli/tests/integration/fixtures/config/mongodb_cluster.json
- das-cli/tests/integration/fixtures/config/redis_cluster.json
- das-cli/tests/integration/fixtures/config/simple.json
- das-cli/tests/integration/test_config.bats
- das-runner-manager/scripts/entrypoint.sh
- das-runner-manager/src/cli/commands/start_command.py
Closes https://github.com/singnet/das/issues/190
> [das#190]: Implement deployment scripts for system components in VULTR servers

- .github/workflows/run-das-cli-tests.yml
- das-cli/src/commands/config/config_cli.py
- das-cli/src/commands/inference_agent/__init__.py
- das-cli/src/commands/inference_agent/inference_agent_cli.py
- das-cli/src/commands/inference_agent/inference_agent_container_manager.py
- das-cli/src/commands/inference_agent/inference_agent_module.py
- das-cli/src/commands/link_creation_agent/link_creation_agent_container_manager.py
- das-cli/src/das_cli.py
- das-cli/src/settings/config.py
- das-cli/tests/integration/fixtures/config/mongodb_cluster.json
- das-cli/tests/integration/fixtures/config/redis_cluster.json
- das-cli/tests/integration/fixtures/config/simple.json
- das-cli/tests/integration/test_config.bats
Resolves https://github.com/singnet/das/issues/323
> [das#323]: Deploy the component Inference Agent

- das-cli/src/commands/config/config_cli.py
- das-cli/src/commands/db/redis_container_manager.py
- das-cli/src/common/network.py
> [#163] Fix das-cli Redis Cluster setup

- das-cli/tests/integration/test_faas.bats
- das-cli/tests/integration/test_inference_agent.bats
- das-cli/tests/integration/test_logs.bats
> [#171]: Implement missing test cases in das-cli

- das-cli/src/commands/das/das_cli.py
- das-cli/src/common/command.py
> [#173] Fix Remote Command Execution in das-cli

- das-cli/src/commands/db/db_cli.py
- das-cli/src/common/docker/container_manager.py
- das-cli/tests/integration/libs/docker.bash
- das-cli/tests/integration/test_db.bats
Closes https://github.com/singnet/das/issues/558
> [das#558] Add prune parameter to das-cli db stop to remove container volumes

- das-cli/src/commands/config/config_cli.py
- das-cli/src/common/config/store.py
- das-cli/src/common/settings.py
Closes https://github.com/singnet/das/issues/627
> [das#627] Fix das-cli behavior to overwrite existing config files when generating new ones

- BUGFIXES
- das-cli/src/commands/inference_agent/inference_agent_cli.py
- das-cli/src/commands/inference_agent/inference_agent_module.py
- das-cli/tests/integration/test_inference_agent.bats
Closes https://github.com/singnet/das/issues/688
> [das#688]: Remove dependency Inference agent -> LCA in das-cli

- das-cli/tests/integration/test_db.bats
Closes https://github.com/singnet/das/issues/688
> [das#688] [HOTFIX] Update test_db.bats to expect 4 MongoDB nodes

- CHANGELOG
- das-cli/src/commands/config/config_cli.py
- das-cli/src/commands/link_creation_agent/link_creation_agent_cli.py
- das-cli/src/commands/link_creation_agent/link_creation_agent_container_manager.py
- das-cli/src/settings/schema.json
- das-cli/tests/integration/fixtures/config/mongodb_cluster.json
- das-cli/tests/integration/fixtures/config/redis_cluster.json
- das-cli/tests/integration/fixtures/config/simple.json
- das-cli/tests/integration/test_config.bats
Closes https://github.com/singnet/das/issues/678
> [das#678] Remove LinkCreationAgent config parameters from das-client setup

- .vscode/launch.json
- das-runner-manager/scripts/entrypoint.sh
- das-runner-manager/src/api_server/containers/containers.py
- das-runner-manager/src/api_server/main.py
Closes https://github.com/singnet/das/issues/762
> [das#762] Recreate container from scratch instead of just restarting

- das-cli/README.md
- das-cli/src/commands/context_broker/context_broker_cli.py
- das-cli/src/commands/evolution_agent/evolution_agent_cli.py
- das-cli/src/commands/example/example_cli.py
- das-cli/src/commands/inference_agent/inference_agent_cli.py
- das-cli/src/commands/link_creation_agent/link_creation_agent_cli.py
- das-cli/src/commands/query_agent/query_agent_cli.py
Closes https://github.com/singnet/das/issues/682
> [das#682] Review all das-cli documentation to replace low port numbers by larger ones
